### ISSUE TITLE
Сверстать макет primerStatii.psd

### ISSUE THREAD

**Issue by NataliaVolik** [greensoftkg/brand-maker#2]
# Легенда

По [макету primerStatii.psd](https://github.com/greensoftkg/brand-maker/blob/master/design/primerStatii.psd) сделаю верстку. 
Верстку буду делать с помощью следующих технологий:
* [Gordondalos/zagotovka](https://github.com/Gordondalos/zagotovka) - как основа, каркас
* SASS вместо чистого CSS
* Для автоматической компиляции SASS в CSS - GULP

## Логическое разделение
будет таким
![logicsections](https://cloud.githubusercontent.com/assets/14816149/11014233/462367f6-8558-11e5-8f22-650020a4143b.png)

## Меню
![menu](https://cloud.githubusercontent.com/assets/14816149/11014200/d5f02236-8556-11e5-8191-af305afd4aa7.png)
Ссылки "Заказать звонок" и "Схема проезда" будут заглушками:
```
<a href="#">..</a>
```

Данное меню будет статично, и при прокрутке страницы оно будет "уезжать" как и весь остальной статичный контент.

## Мобильная версия сайта
в дизайне она не предоставлена, поэтому я ее не делаю.

**Comment by NataliaVolik** [comment]
Проблема позиционирования, ветка iss2_positionIssue

**Comment by AlexKalinin** [comment]
Починил, см. коммит ae94ff6
